apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-credentials
  namespace: ecommerce
spec:
  encryptedData:
    .dockercfg: AgCd10TCz7n52Fqwi6Hjj60EqhAsW+dsUSBsG/H/GsAU9S4y4SrUVkkQzNMTNamJHLChKc1D4TvCmJO9Up6GPG7H8yrIBBlNrJIi7ozxW8KOsW3kkAuiAV940QOwS0HPEh1SM45iCQfEvaTbC7USgnoArWpnQrjsDDK0E2Y/BpCIgmShRZVrG/rO7txY9xvuU2hqh5LRXNqk7kyho1FqOeN+6uxtYih90Uu+nYMbLuuo3t0iKOJaRcQU/wq3GDj+zdQhCDVwEJ5LZEMH/ET0SrdPLqzKReoQasYv07QFE5hFtlNfx7GYTVOOJu6ix6hzxtrNAiDj3Bt/Vw+/TsTUktgyh0yOoGborKetFpd5fYykvK2Dwd9XG5gjtp/k9UXAfuqASb8erTwAvhFiD5YHf+VQk+K8I1llvVOrR6vLbxAGrkPu7lYEtmyh4BOEA0oeoWv477i45RsTivakQzFFalrAzaBrf+I6C1UmjJgWARhOee2+NA/TO/LFZmyCo/A0oURSYt6FgcvW0dgLK6tfhJ+sNm9oxgNZ/bdKFACyuX8SJjQrlRhpfIdMJsTdFdFGlEhYIj7L/ZVtzC8HMoWtoLGnwMBh5JAR/xP69VJmO6blViteJivzlt7NyHl1G9v+csNOBxCBda6ZdkaMd/rtpA6B+WamECscAUod2WfL9KF9XhI+Ca++bUNz45+515jy2cEaTmz5JZMR8tk5bjHMxqLkbuszkPWd+2WpeNjrz8xLMM7OP4LVQb0RvXEDDnzkG94v4dCf7ZQ/
  template:
    metadata:
      creationTimestamp: null
      name: docker-credentials
      namespace: ecommerce
    type: kubernetes.io/dockercfg
---
